### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by QueenElizabeth69** [ayoubsiray/gmail_attacker#3]
Someone that stole my phone and deleted so much from it including images and texts.
Can you please help get them back?

**Comment by ghost** [comment]
This is Github...

**Comment by hoseineshghi** [comment]
Hello and politeness. I came across this picture while hacking my own Gmail, which is now hacked:
202/358212 Traceback (most recent call last): File "gmail_attacker.py", line 74, in <module> login() File "gmail_attacker.py", line 58, in login server.login(user_name, password) File " /data/data/com.termux/files/usr/lib/python 2.7/smtplib.py", line 611, in login AUTH_PLAIN + " " + encode_plain(user, password )) File "/data/data/com. termux /files/usr/lib/python 2.7/smtplib.py", line 395, in docmd return self. getreply() File "/data/data/com.termux/files/usr/lib/python 2.7/ smtplib.py", line 369, in getreply raise SMTPServerDisconnected("Connection unexp ectedly closed") smtplib. SMTPServerDisconnected: Connection unexpec tedly closed $
What should I do now?

**Comment by Bradyj1** [comment]
access denied

**Comment by AyoubSirai** [comment]
I didn't expect that this little piece of code would earn all these stars :)

**Comment by Musiciangh** [comment]
Hello and politeness. I came across this picture while hacking my own Gmail, which is now hacked:
Traceback (most recent call last):
  File "gmailhack.py", line 55, in <module>
    login()
  File "gmailhack.py", line 39, in login
    server.login(user_name, password)
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 611, in login
    AUTH_PLAIN + " " + encode_plain(user, password))
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 395, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 366, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1946)

**Comment by Rahman2326** [comment]
> Someone that stole my phone and deleted so much from it including images and texts. Can you please help get them back?

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my WhatsApp number +8801314956025
